#!/bin/sh

version=$(git describe --match "v[0-9]*" --abbrev=4 HEAD 2>/dev/null ||
    git rev-parse --short HEAD)
git update-index -q --refresh
if [ ! -z "$(git diff-index --name-only HEAD --)" ]; then
    version="$version-dirty"
fi

if [ -r VERSION-FILE ]; then
    v=$(sed -e 's/^VERSION = //' < VERSION-FILE)
else
    v=unset
fi

if [ "$version" != "$v" ]; then
    echo "VERSION = $version" > VERSION-FILE
fi
